### ISSUE TITLE
Character Token Position.Position is off by 1 where underlying stream content for said token started with '\r'

### ISSUE THREAD

**Issue by cmwoods** [AngleSharp/AngleSharp#786] opened 2019-04-30 00:56 UTC
### Prerequisites

- [Y] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [Y] Are you running the latest version of AngleSharp?
- [Y] Did you check the FAQs to see if that helps you?
- [Y] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [Y] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

Tokenization of TextSource appears to be "eating"/suppressing carriage return - but only if it is the first character of a Character token.

### Steps to Reproduce

1. Create a memory stream with an initial value/buffer of `<html><body><p>\r\nThis is test 1<p> \r\nThis is test 2</body></html>`.
2. Create a TextSource instance passing the memory stream as the first parameter.
3. Enumerate the tokens returned from calling `Tokenize()` extension method on that TextSource.

For each token, the token's Position.Position-1 (separate bug to be reported here) should be the index back into the TextSource for the starting character of the token and the TextSource's Index should be the index for the first characters after the end of the current token. As such, you should be able to get the "raw text" of the token by doing a substring on TextSource's Text() property using the start index and computing the length (end index - start index).

**Expected behavior:** [What you expected to happen]
The "raw text" of the first Character Token should be `"\r\nThis is test 1"`.
The "raw text" of the second Character Token should be `" \r\nThis is test 2"`.

**Actual behavior:** [What actually happened]
The "raw text" of the first Character Token is actually `"\nThis is test 1"`.
The "raw text" of the second Character Token is the expected `" \r\nThis is test 2"`.

Looking at the Character Token's Data property it appears that the carriage return is always suppressed (or if only carriage return appears and no following linefeed then the carriage return is replaced with linefeed. As such, it is not initially obvious that the token's reported starting position is off by one - however this is a problem if you ever need to inject something before the start of the character token as you would be inserting into the middle of a CRLF sequence.

**Environment details:** [OS, .NET Runtime, ...]
Windows, Visual Studio 2019, .NET Framework 4.6, Any CPU (pref 64-bit)

### Possible Solution

I took a very quick peek into the code and it appears that this might have something do due with AngleSharp.Common.BaseTokenizer.NormalizeForward which seems to skip over the carriage return character. I did not however attempt to trace down through.

**Comment by FlorianRappl** [comment] 2019-04-30 13:24
Actually both CRs should be suppressed. I will look into this.

By W3C spec CRLF needs to be normalized to LF.

**Comment by FlorianRappl** [comment] 2019-04-30 22:25
Something does not seem right. I have the following tests that shows up green for me ...

```cs
[Test]
public void TokenizationCarriageReturnPureCharactersIssue_786()
{
    var ms = new MemoryStream(Encoding.UTF8.GetBytes("\r\nThis is test 1\r\nThis is test 2"));
    var s = new TextSource(ms);
    var t = CreateTokenizer(s);
    var token = t.Get();
    Assert.AreEqual(HtmlTokenType.Character, token.Type);
    Assert.AreEqual("\nThis is test 1\nThis is test 2", token.Data);
}

[Test]
public void TokenizationCarriageReturnNonLeadingIssue_786()
{
    var ms = new MemoryStream(Encoding.UTF8.GetBytes("<html><body><p>\r\nThis is test 1<p> \r\nThis is test 2</body></html>"));
    var s = new TextSource(ms);
    var t = CreateTokenizer(s);
    var tokenHtmlOpen = t.Get();
    var tokenBodyOpen = t.Get();
    var tokenP1 = t.Get();
    var tokenP1data = t.Get();
    var tokenP2 = t.Get();
    var tokenP2data = t.Get();
    var tokenBodyClose = t.Get();
    var tokenHtmlClose = t.Get();
    var eof = t.Get();
    Assert.AreEqual(HtmlTokenType.EndTag, tokenHtmlClose.Type);
    Assert.AreEqual(HtmlTokenType.StartTag, tokenHtmlOpen.Type);
    Assert.AreEqual(HtmlTokenType.EndTag, tokenBodyClose.Type);
    Assert.AreEqual(HtmlTokenType.StartTag, tokenBodyOpen.Type);
    Assert.AreEqual(HtmlTokenType.StartTag, tokenP1.Type);
    Assert.AreEqual(HtmlTokenType.StartTag, tokenP2.Type);
    Assert.AreEqual(HtmlTokenType.Character, tokenP1data.Type);
    Assert.AreEqual(HtmlTokenType.Character, tokenP2data.Type);
    Assert.AreEqual(HtmlTokenType.EndOfFile, eof.Type);
    Assert.AreEqual("\nThis is test 1", tokenP1data.Data);
    Assert.AreEqual(" \nThis is test 2", tokenP2data.Data);
}
```

What am I doing wrong?

**Comment by cmwoods** [comment] 2019-05-01 19:21
The key lies in two things:

1. Your testing is looking at the HtmlToken.Data whereas I'm looking at the "raw text" from the TextSource corresponding to the token:
```
...
var token = t.Get();
int tokenStart = token.Position.Position - 1;
string rawText = s.Text.Substring(tokenStart, s.Index - tokenStart);
...
```
2. I should have expressed the issue better - the crux of the issue lies buried in the following paragraph:

> Looking at the Character Token's Data property it appears that the carriage return is always suppressed (or if only carriage return appears and no following linefeed then the carriage return is replaced with linefeed). **_As such, it is not initially obvious that the token's reported starting position is off by one_** - however this is a problem if you ever need to inject something before the start of the character token as you would be inserting into the middle of a CRLF sequence.


I should have more clearly stated that the problem is the reported token start position being incorrect and then saying it is easy to see that this has happened by looking at the "raw text" based on the token's returned start position. The other way to notice this is of course if you explicitly count out the expected Position.Position values for each and every token and then compare the actual vs. expected however I found that, for me at least, it is easier to check the "raw text" as that test can be generalized against any HTML input stream.

**Comment by FlorianRappl** [comment] 2019-05-01 19:29
I'm a little bit confused (maybe due to the title).

So if I form the problem in my words I would now say "the position in the original text / stream where the token's index is leading to is off by one in case of CRLF -> LF normalization". Would you agree?

**Remark**: The initial statement

> As such, you should be able to get the "raw text" of the token by doing a substring on TextSource's Text() property using the start index and computing the length (end index - start index).

will in general not be achievable. Reasons are stream normalization and the general W3C tokenization algorithm.

**Comment by cmwoods** [comment] 2019-05-02 16:47
Again - sorry for the initial confusion of my poorly worded issue submission. Yes I would agree with your statement with the addendum that this only is happening when the first character to read when pulling the [character] token from the stream is '\r'.

[As an aside - as this really isn't part of the issue] I'm not sure why you say that the "raw text" approach that I'm trying to do is not generally achievable. Perhaps it would be best to take this part of the discussion offline from the issue.

**Comment by FlorianRappl** [comment] 2019-05-03 11:53
No problem I think we can solve this with the next release. From my point of view the issue is now clear and can be reproduced well.

Regarding the other topic:

> [As an aside - as this really isn't part of the issue] I'm not sure why you say that the "raw text" approach that I'm trying to do is not generally achievable. Perhaps it would be best to take this part of the discussion offline from the issue.

The issue is that tokens represent a logical unit consumable by the parser. As such they are already normalized (to meet the parser's expectations / help the parser sufficiently) and may not 100% match the "raw text".

**Comment by cmwoods** [comment] 2019-05-03 18:41
Ah - okay. I see. Yes I agree with you on that as to what the parser and/or any other users of the HtmlTokenizer may need from the HTML document content: use the normalized data representation and not the raw data. My particular case is a little different probably than most so I don't expect it likely that others would try to pull raw text as I was doing.

**Comment by FlorianRappl** [comment] 2019-05-22 20:09
Landed in `devel`.

**Closed as completed by FlorianRappl** 2019-05-22 20:09 UTC
Labels: bug, parser
