### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by zhuzhiyuan** [AngleSharp/AngleSharp#597] opened 2017-10-09 08:08 UTC
version 0.9.9
```
在 System.Runtime.CompilerServices.ConditionalWeakTable`2.VerifyIntegrity()
在 System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key,TValue value)
在 AngleSharp.Dom.Document..ctor(IBrowsingContext context,TextSource source)
在 AngleSharp.Parser.Html.HTMLPaser.Parse(String source)
```

**Comment by FlorianRappl** [comment] 2017-10-09 11:38
Duplicate of #556.

**Closed as completed by FlorianRappl** 2017-10-09 11:38 UTC
Labels: duplicate
