### ISSUE TITLE
Cookie format error reported when accessing twitter.com

### ISSUE THREAD

**Issue by pmoran1947** [AngleSharp/AngleSharp#598] opened 2017-10-09 09:58 UTC
When I attempt to open the url https://twitter.com

I get an exception that reports the error is 

"Cookie format error."

The cookie value is 

personalization_id="v1_JOjIS3MDab0BCWZA7NeNzA=="; Expires=Wed, 09 Oct 2019 09:42:10 UTC; Path=/; Domain=.twitter.com,guest_id=v1%3A150754213082485945; Expires=Wed, 09 Oct 2019 09:42:10 UTC; Path=/; Domain=.twitter.com
The code I am using is 

            var config = Configuration.Default.WithDefaultLoader().WithCookies();
            var browsingContext = BrowsingContext.New(config);

            await browsingContext.OpenAsync("https://twitter.com");

**Comment by FlorianRappl** [comment] 2017-10-09 11:37
I guess this could be a duplicate of #519.

**Closed as completed by FlorianRappl** 2017-10-09 11:37 UTC
Labels: duplicate
