### ISSUE TITLE
pretext and posttext properties.

### ISSUE THREAD

**Issue by mikefulton63** [AngleSharp/AngleSharp#1208] opened 2024-11-22 07:06 UTC
### Description

I've been trying AngleSharp and while I'm mostly happy with it, there are some annoying gaps in functionality.  It's not impossible that it's simply a failure to understand something on my part, so if anyone has advice, please let me know. Here's what I am trying to figure out at the moment. Given a chunk of HTML that looks like this:

```
<div class="blu">
       <label>Type</label>
        <img src="/ss.png" style="height:12px; margin-top:2px;" />
              Solid state
</div>
```

There seems to be no good way to get at the text "Solid State" that follows the IMG tag, except via the **InnerHtml** of the surrounding **DIV** -- and of course then you have the **label** and **img** tags as well. which you don't want.  

I am currently using a brute-force solution and would like to figure out something more elegant if possible.  This seems to be an issue with self-closing tags like IMG and BR.

My first thought for a solution was to add pair of properties named (for example) "**pretext**" and "**posttext** which would return anything before or after the current element that wasn't part of another tag.

**Comment by FlorianRappl** [comment] 2024-11-23 08:23
Is the objective that you have to get the text **node** or just the text **content**? While the former is "hard" (i.e., not covered by things like `querySelector` in the official standard) the latter is a standard case that you can get via `innerText` of any node (e.g., of the `div` element in this case).

It's true that there are various text nodes that will be included in an `innerText` / text computation. In the example above we see multiple newline + whitespace text nodes that will in one way or another influence that outcome. That being written - in the given example the solution would be `QuerySelector("img").NextSibling.TextContent`.

**Comment by mikefulton63** [comment] 2024-11-23 09:00
I want the text content. As far as I can determine there is no "text node" here.  In fact, that seems to be root of the issue. The other bits contained within the DIV are counted as children, but not the tagless text. 

If that text isn't counted as a child then how can it be a sibling of either of the other two elements?  

I've walked up and down the children-parent tree here and I've never seen the text anywhere except the **innerhtml** of the div.

My working (albeit inelegant) solution is to take the inner html and then subtract the text of the DIV's other children. and the extraneous tab and newline characters.  It works here but I fear it is a fragile solution that will break at some point.

I am not sure I understand your suggestion about using **QuerySelector("img").NextSibling**.  There are dozens, maybe hundreds of places with similar bits of HTML.  Wouldn't the QuerySelctor idea return a collection to all of them? How would I aim it at the specific block I want ?

**Comment by FlorianRappl** [comment] 2024-11-23 13:10
I think you may misunderstand the project / project goals. We follow W3C standards. `querySelector` is a standard and only operates on elements - not nodes. Every element is a node, but not every node is an element (e.g., a text node is not an element).

So:

> Wouldn't the QuerySelctor idea return a collection to all of them?

That's a question you need to address to the W3C board - AngleSharp just implements the standard. The standard defines a query selector / CSS (which is where the selectors are defined) to be only operational on elements.

> As far as I can determine there is no "text node" here.

I don't think that's true. There definitely are such nodes. Every piece of text is contained in a text node.

> The other bits contained within the DIV are counted as children, but not the tagless text.

There are `children` (https://developer.mozilla.org/en-US/docs/Web/API/Element/children) and `childNodes` (https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes). You look at the wrong collection. `children` is essentially just `childNodes` constraint to `Element` type of nodes. `childNodes` is *all* the nodes contained in a `Node`.

Hope that helps!

(I close the issue as I think the problem is rather dealing with web standards than AngleSharp itself. Of course, we are always open to include helpers if they add value - in such cases just open a new issue with a proposal what helper to implement or even better a PR with the helper; then we can discuss such helpers)

**Closed as completed by FlorianRappl** 2024-11-23 13:10 UTC
Labels: enhancement

**Comment by mikefulton63** [comment] 2024-11-24 21:11
I have already used "Nodes" for some things and as far as I could determine, in this situation it did not seem to have any path to get to the text that was any different from what I was getting from "Children".  But maybe I missed something, so I'll have another look.

If you're suggesting that I should get a node for the **LABEL** element, another for the **IMG** element, and one for the loose text, I don't think that's consistent with what I've been seeing.  But as I said, I'll have another look to be sure.

I suspect that what I'm going to find is a node that contains the **InnerHtml** of the DIV which would mean I'll still have to manually remove the sibling elements.

Either way, thanks for your response.
