### ISSUE TITLE
Install-Package AngleSharp results in Depency Loop Detected error

### ISSUE THREAD

**Issue by HerbM** [AngleSharp/AngleSharp#925] opened 2021-01-02 22:15 UTC
# Bug Report
Thanks for doing so much work on this package, probably something with my environment so detail on that is included below.

## Description

Installing on Windows 10 as Administrator, with both PowerShell 7.2 Preview (1 & 2) and Windows PowerShell 5.1 results in an error showing Depency Loop after long delay:

  **Install-Package: Dependency loop detected for package 'AngleSharp'.**
## Steps to Reproduce
```
> Install-Package AngleSharp -Version 0.14.0
Install-Package: Dependency loop detected for package 'AngleSharp'.

# Also tried other combinations, e.g., ...
Install-Package AngleSharp -RequiredVersion 0.14.0 -scope AllUsers -force -Source Nuget.org

```
**Expected behavior:** [What you expected to happen]
Successful install of the package.

**Actual behavior:** [What actually happened]

**Environment details:** 
    PSVersion                      7.2.0-preview.2
    PSVersion                      5.1.21277.1000

    [OS, .NET Runtime, ...]
    .NET SDK (reflecting any global.json):
     Version:   5.0.200-preview.20601.7
     Commit:    b3b934bbf2

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.21277
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

    Host (useful for support):
      Version: 5.0.0
      Commit:  cf258a14b7

    .NET SDKs installed:
      2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
      2.1.700 [C:\Program Files\dotnet\sdk]
      2.1.801 [C:\Program Files\dotnet\sdk]
      3.1.301 [C:\Program Files\dotnet\sdk]
      3.1.401 [C:\Program Files\dotnet\sdk]
      5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

    .NET runtimes installed:
      Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download

## Possible Solution
None discovered yet:
Searching issues for [ is:issue dependency loop ] gave no matches.
FAQ has no mention of "Dependency Loop" and references to "install" did not discuss issue.
Change log here stops with version 12.0: https://anglesharp.github.io/log.html

**Comment by FlorianRappl** [comment] 2021-01-02 22:51
This is the changelog: https://github.com/AngleSharp/AngleSharp/blob/master/CHANGELOG.md

I actually never heard of (or experienced) such an error.

Can you give a trace or debug why there should be a dependency loop? Maybe its due to a beta of .NET 5?

Posting more details on the install request (e.g., what kind of project was used) would be desired. Can you provide a MWE that I can run to reproduce the issue?

**Comment by HerbM** [comment] 2021-01-03 03:06
@FlorianRappl 

Thanks for responding...

I'll attach the trace.

This is a minimal example since it is the install itself that fails & that is using the command given on the Nuget page for AngleSharp, never got as far as an actual project.

Initially I left out the Verbose/Debug trace since it went on seemingly forever and I didn't know at what point (if any) it started repeating.

There are repeated lines but not a great many.

[AngleSharpTrace.txt](https://github.com/AngleSharp/AngleSharp/files/5761134/AngleSharpTrace.txt)

**Comment by FlorianRappl** [comment] 2021-01-03 10:12
Not sure what to make of this.

> This is a minimal example since it is the install itself that fails & that is using the command given on the Nuget page for AngleSharp, never got as far as an actual project.

I cannot follow here. A minimal example would involve a csproj file to see to what project you want to add the dependency. Not sure where else you'd install it.

The trace looks rather that your system has a lot of issues resolving NuGet dependencies (such as AngleSharp itself, then System.Text.Encoding.CodePages, then ..., finally NETStandard.Library). The last one ultimately fails after exhausting retries.

Right now this does not look like an issue with AngleSharp but rather with the specific setup / .NET. A MWE project to reproduce this would be good.

**Comment by HerbM** [comment] 2021-01-03 10:39
@FlorianRappl 

Seems completely reasonable that this is something local, though I have no idea or experience with fixing Nuget installs.

I had no intention of creating a  CSharp project or similar.

My goal was to install the package and then create .NET objects from it using PowerShell.

Maybe that is not possible, but the first first step would be simply installing the project to the system to make it available.

For now, all I want to do is install the package.  Is this not a reasonable thing to do?

**Comment by FlorianRappl** [comment] 2021-01-04 10:33
> For now, all I want to do is install the package. Is this not a reasonable thing to do?

Sure, but I fear that AngleSharp does not officially support PowerShell yet. See #870 for another issue with PowerShell. I would love to support this, but that will only work by external contributions. Any help on the topic appreciated.

**Comment by HerbM** [comment] 2021-01-04 18:43
@FlorianRappl 
Whether I can get it to work from PowerShell is my next problem AFTER it cleanly installs.

There is nothing I am reporting here that is related to PowerShell except the use of the Install-Package command given on the Nuget page.

However, do you have any idea how I can go about verifying or cleaning up my .NET to make the provided command work?

Perhaps you (or someone) could try the command given on the Nuget page with WIndows 10 where AngleSharp has not yet been installed?  

Install-Package AngleSharp -Version 0.14.0

### I am going to arrange to try it on some other machines, and to do a direct download and see if that can be make the install work.

**Comment by FlorianRappl** [comment] 2021-01-04 20:48
The error is not from `AngleSharp`, but from `System.Text.Encoding.CodePages`.

So there is nothing we can do in here - the bug needs to be reported there.
(if you try installing `System.Text.Encoding.CodePages` you'll hit the dependency loop, which you'll therefore hit on any package depending on `System.Text.Encoding.CodePages` - this is an official MS dependency)

**Comment by HerbM** [comment] 2021-01-08 15:51
@FlorianRappl 
Thank you so much for that help.
It's been failing on other machines for other people also, and I've been given another hint that it is some sort of obsolete link in the Nuget URI (perhaps).

I'll work on that and report it at System.Text.Encoding.CodePages if I can't work out the answer.

Thanks again.

**Comment by FlorianRappl** [comment] 2021-01-08 15:58
As written @HerbM it will fail on all machines. `System.Text.Encoding.CodePages` is one of the dependencies of AngleSharp, and this one has a problem.

So as long as this is not fixed in `System.Text.Encoding.CodePages` all dependent packages such as `AngleSharp` will keep failing, too.

**Closed as completed** 2021-01-10 07:00 UTC
Labels: bug

**Comment by patware** [comment] 2021-09-30 16:06
Found a "workaround" ?

Installed AngleSharp from nuget.exe, then install-package but specifying -SkipDependencies

`
> nuget install AngleSharp
> Install-Package 'AngleSharp' -Scope 'CurrentUser' -Source 'Nuget.org' -SkipDependencies
`

PSVersion                      7.1.4
PSEdition                      Core

If this helps others.

**Comment by ZzZombo** [comment] 2022-12-15 02:57
What areas of the library are affected if the dependencies aren't installed?
