### ISSUE TITLE
Nested tables nodes enumerating

### ISSUE THREAD

**Issue by aibondarenko** [AngleSharp/AngleSharp#63] opened 2015-02-26 10:30 UTC
I have table (1 tr, 1 td inside it) which contains another table (1 tr, 1 td inside it) (will refer it futher to nested tables). When i try to get a rows from an upper one by means of this piece of code:

AngleSharp::DOM::Html::IHtmlTableElement^ aTableNode = ...;
AngleSharp::DOM::IHtmlCollection^ rowsCollection = aTagNode->Rows;

i got 2 rows in "rowsCollection" - one for an upper table and one for nested. As far as i understood, "Rows" property (as well as "Cells") run recursive on upper table and process all underlying tables, which is not always what user might want.

Is there a natural way to get just one table (i.e. row, which is child of upper table) row in this case? Of course, one can post-process recursive list (to get rid of underlying table nodes), but it looks a bit like a hack.

All mentioned above hold true for cells within a row.

Tnx in advance.

**Comment by FlorianRappl** [comment] 2015-02-26 20:46
Hm, I am not sure if that is not a bug in my code. I will cross-check with the official specification to be sure, that the `Rows` property actually behaves right. From an intuitive POV I would say that the `Rows` property should only return the rows for the provided table, not nested ones.

I will investigate! Thanks for the point that out ...

**Comment by FlorianRappl** [comment] 2015-02-26 22:45
Yes, this is a bug - will be fixed.

**Closed as completed** 2015-02-27 21:45 UTC
Labels: bug
