### ISSUE TITLE
"initial" value in css serialization text

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#73] opened 2015-03-04 19:11 UTC
When parsing the following sample styles and serialized back to css text, I got quite different output from the original definition:

.T1 { list-style: none; }  
.T2 {border: 1px outset; }

The end result css text is:
.T1 { list-style: initial initial initial;; }  
.T2 {border: 1px outse initialt; }

For T2, it would be nice to ends up with the same original css text; for T1, it actually renders different result in browser.

I also noticed that things like "ButtonFace", "currentColor" and the "filter" property is not currently supported. On they on the roadmap? 

Thanks!

**Comment by FlorianRappl** [comment] 2015-03-04 19:20
As far as the colors are concerned `currentColor` is context specific and is already _somehow_ supported in the supporting contexts (it is not allowed everywhere). However, since no real CSS computation is taking place, the exact color cannot be determined, which makes the value useless. But it will come (and it supported in that sense, that values containing `currentColor` are matched as being invalid).

The `ButtonFace` (as all other system colors) is currently not included, but will be at some point in the future. The only question is: How to configure AngleSharp which colors to use? These are system colors and since AngleSharp is a PCL, it basically knows nothing about the system. Probably a service seems like a good idea. I don't know yet, but it will be supported, I guess already in v0.9.

The original concern is definitely justified. Serializing the `initial` is basically no problem, however, it is a cosmetic issue (and will be fixed). The declaration for **T1** seems fishy - I will check for a bug.

**Comment by FlorianRappl** [comment] 2015-03-06 16:05
As far as the `T1` selector is concerned I can't reproduce the problem (the declaration is valid, as it should be). I will fix the other representation as discussed.

**Comment by D92130** [comment] 2015-03-06 17:52
Thanks for looking into the issue.
Here is the code I use to reproduce the T1 selector issue:

```
        string cssSrc = ".T1 { list-style: none; }";
        var stylesheet = AngleSharp.Parser.Css.CssParser.ParseStyleSheet(decl);
        string cssText = stylesheet.CssText;
```

And the cssText value at the end is ".T1 { list-style: initial initial initial; }" .

**Comment by D92130** [comment] 2015-03-06 17:53
Sorry, mistake in the sample code, fixed here:

```
    string cssSrc = ".T1 { list-style: none; }";
    var stylesheet = AngleSharp.Parser.Css.CssParser.ParseStyleSheet(cssSrc);
    string cssText = stylesheet.CssText;
```

**Closed as completed** 2015-03-07 16:29 UTC
Labels: bug
