### ISSUE TITLE
An error occurred when parsing the Cookie header for Uri

### ISSUE THREAD

**Issue by Jordan-Hall** [AngleSharp/AngleSharp#477] opened 2016-12-01 20:57 UTC
Configuration:
`var configuration = Configuration.Default.WithDefaultLoader().WithCookies();
        var context = BrowsingContext.New(configuration);
        await context.OpenAsync("https://online.lloydsbank.co.uk/personal/logon/login.jsp");`

Version: 0.9.9 using .net core

Cookie:
`"IBCOOKIE03=IBCOOKIE03VALUERANDYOQFX2dxUnuKzGxKugkyog0dGja829Dq, TLCookie=RANDHINY9D0GK0FyUOckPRQQ4pwKBUd72rHr, $Version=1; IBCOOKIE02=fbe4e2a56166f5f2017d1261b57b4f9703d00d0891fdd334b50a00af690fa67d4d9391675d51a02ae7df2bcfcaaa230c76bNFKbewS4Q+UWQp6do6h4T4vWKYetCZ9QoH5L9jqzZ4jNoI02nJYAEu33UkOpiceGzyYp7S7JIvN8BmAg3aQ==; $Path=/; $Domain=.lloydsbank.co.uk"`

**Comment by FlorianRappl** [comment] 2016-12-01 21:05
Thanks, but please read the guide for posting issues first.

You are missing:

- MWE to reproduce it (your configuration?)
- Which version of AngleSharp you are using

Thanks!

**Comment by Jordan-Hall** [comment] 2016-12-01 21:16
@FlorianRappl  sorry about that. I've updated it.

**Comment by FlorianRappl** [comment] 2016-12-01 23:20
Thanks for the code. I can confirm this. I am not sure if this can be fixed easily (potentially the bug is within the cookie container, but hopefully its just me doing something wrong with the transformations up front).

Will be fixed for v0.10.

**Comment by FlorianRappl** [comment] 2016-12-06 23:13
The problem is definitely on my side, simply ignoring the optional path portion - which may lead to exceptions from the container (consistency check).

**Comment by FlorianRappl** [comment] 2016-12-07 08:25
Fixed, see PR #488.

**Closed as completed by FlorianRappl** 2016-12-07 08:25 UTC
Labels: bug, network
