### ISSUE TITLE
Gzip encoding

### ISSUE THREAD

**Issue by pettijohn** [AngleSharp/AngleSharp#1122] opened 2023-06-14 14:54 UTC
# Bug Report

## Prerequisites

- [Y ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ Y] Are you running the latest version of AngleSharp?
- [?] Did you check the FAQs to see if that helps you?
- [Y] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [Y] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

I'm seeing the same issue as #416 - downloaded page is gzip encoded and AngleSharp is not decompressing it. 

## Steps to Reproduce

Does not work:
```
var config = Configuration.Default.WithLocaleBasedEncoding().WithDefaultLoader();
var address = "https://www.powerball.com";
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(address);
```

**Expected behavior:** [What you expected to happen]

Document should be decompressed plain text. 

**Actual behavior:** 

Document is "garbled" gzipped content. 

**Environment details:** [OS, .NET Runtime, ...]

Windows 11 x64, .NET 7.0.302, AngleSharp 1.0.3

## Possible Solution

Works:
```
HttpClientHandler handler = new HttpClientHandler()
{
    AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
};        
var http = new HttpClient(handler);
var body = await http.GetStringAsync("https://www.powerball.com");

var config = Configuration.Default;
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(req => req.Content(body));
```

Working around this by using HTTP Client. Is this the recommended approach? I searched for "org:AngleSharp gzip" and didn't see any recommendations or FAQ guidance. I assume this should be out-of-box automatic behavior, so maybe I'm missing something.

**Comment by FlorianRappl** [comment] 2023-06-14 16:50
> Working around this by using HTTP Client. Is this the recommended approach?

Yes, the requester coming with AngleSharp is not using the HttpClient and should only be used in simple cases. If you heavily rely on IO then you should use AngleSharp.Io.

I'll see if this is a general problem with the requester (not being able to process gzip) or if this is something with the page. If its a general problem then we need to drop the "gzip" from [accepted encodings](https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Io/DefaultHttpRequester.cs#L54).

**Comment by FlorianRappl** [comment] 2023-06-23 15:50
I just tested this and it works for me. Sure, that this was not just some problem with the underlying .NET libs or the OS? Tested against `powerball.com` and can correctly read the page.

**Comment by pettijohn** [comment] 2023-06-23 16:32
Try a few more times, seems to be happening sporadically for me. I suspect they have a few servers in their fleet that are misconfigured, maybe not honoring Accept-Encoding header (though I can't repro that in Postman). .NET 7, Win11 x64, AngleSharp 1.0.3. Here's what I see in two back-to-back runs. 

I don't personally need this fixed as HttpClient works 100% of the time. 

![image](https://github.com/AngleSharp/AngleSharp/assets/632844/3d1c8d96-3f50-4503-a051-34bab996ef96)

![image](https://github.com/AngleSharp/AngleSharp/assets/632844/df013b9c-4acd-43a7-b5f9-c0b33c1391dd)

**Comment by FlorianRappl** [comment] 2023-06-23 17:14
Well, I now even use a loop with 1000 iterations and the result stays the same. The content is always correct.

As already mentioned I think the root issue is their server. And even if it sends back malformed content - .NET should handle that (after all we are not processing the response directly, only after the requester that is provided by .NET). So the root issue is a bug in .NET that should be fixed when the server has a hiccup as seen here.

I try to reproduce this some more times; maybe there is a workaround we can apply - otherwise I'd close this.

**Closed as completed** 2023-06-24 12:07 UTC
Labels: bug, requester

**Comment by FlorianRappl** [comment] 2023-06-24 12:48
By the way I could finally reproduce this. The server is sometimes returning Brotli ("br") compressed responses - even though the `Accept-Encoding` header tells it that only "deflate" and "gzip" are supported.

In such case we'll now throw an exception. The response would have been gibberish anyway and this way one can react. Should be a rare case though - this is certainly a problem on the webserver.
