### ISSUE TITLE
StackOverflowException in document.QuerySelectorAll("a")

### ISSUE THREAD

**Issue by dennisgorelik** [AngleSharp/AngleSharp#523] opened 2017-01-28 14:48 UTC
AngleSharp.dll produces fatal crash (that kills the whole process) when we try to extract links from http://onestop.fiu.edu/financial-aid/loans/ page (that seems safe with only 108 links).
We were able to reproduce this crash on some developers machines, but not on all machines.
Please try to run code below on Windows 7 machine.
```
using AngleSharp.Parser.Html;

[TestMethod]
public void AngleSharpFailureTest()
{
	var pageHtml = LoadPageHtmlContentFromUrl("http://onestop.fiu.edu/financial-aid/loans/"); // This line is a pseudo-code. Please use your own url load method, or load pageHtml from attached AngleSharpFailureTest.html.zip
	var parser = new HtmlParser();
	var document = parser.Parse(pageHtml);
	// The QuerySelectorAll("a") call in the next line:
	// - Works well when running without debugger
	// - Works well on Windows 10 machine with 16 GB RAM under Visual Studio 2013 debugger
	// - Fatally fails on Windows 7 machine with 16 GB RAM under Visual Studio 2013 debugger
	// - Fatally fails on Windows 7 machine with 8 GB RAM under Visual Studio 2013 debugger
	// - Fatally fails on Windows 7 machine with 4 GB RAM under Visual Studio 2013 debugger
	// - Fatally fails on Windows Server 2012 R2 virtual machine with 9 GB RAM under Visual Studio 2013 debugger
	// Fatal failure: "An unhandled exception of type 'System.StackOverflowException' occurred in AngleSharp.dll".
	// That fatal failure kills the whole process, so we cannot catch that StackOverflowException.
	var nodes = document.QuerySelectorAll("a");
	Assert.AreEqual(108, nodes.Length);
}
```
[AngleSharpFailureTest.html.zip](https://github.com/AngleSharp/AngleSharp/files/736935/AngleSharpFailureTest.html.zip)

![image](https://cloud.githubusercontent.com/assets/4333866/22397469/1d3ce102-e540-11e6-9c4f-28672a574c69.png)

**Comment by campersau** [comment] 2017-01-28 15:45
The html looks very strange. It contains 25536 self closing`<content />`-tags which is [invalid](https://developer.mozilla.org/en/docs/Web/HTML/Element/content).

**Comment by FlorianRappl** [comment] 2017-01-28 16:33
I think this one is already implicitly solved by #476. Have you tried the latest bits from `devel`?

**Comment by dennisgorelik** [comment] 2017-01-28 17:38
@FlorianRappl 
Are you suggesting to try to build our own AngleSharp library from https://github.com/AngleSharp/AngleSharp/tree/devel ?

**Comment by FlorianRappl** [comment] 2017-01-28 17:55
Yes, of course that's what that means.

**Comment by dennisgorelik** [comment] 2017-01-28 18:46
Should https://github.com/AngleSharp/AngleSharp/tree/devel solution be compilable in Visual Studio 2013?
I am getting 55 build errors, including:
```
Error	4	Invalid expression term '.'	C:\dennis\projects\AngleSharp-devel\src\AngleSharp\Html\LinkRels\StyleSheetLinkRelation.cs	13	62	AngleSharp.Core
Error	5	Syntax error, ':' expected	C:\dennis\projects\AngleSharp-devel\src\AngleSharp\Html\LinkRels\StyleSheetLinkRelation.cs	13	63	AngleSharp.Core
Error	6	} expected	C:\dennis\projects\AngleSharp-devel\src\AngleSharp\Html\LinkRels\StyleSheetLinkRelation.cs	15	10	AngleSharp.Core
```
I have .NET Framework version 4.6.01586 installed.

**Comment by FlorianRappl** [comment] 2017-01-28 19:05
AngleSharp is written in C# 6 and thus requires Roslyn as a compiler. You'll need to use VS 2015+ for development here.

**Comment by campersau** [comment] 2017-01-28 19:07
Yes the exception is also thrown with the `devel` branch.

The problem is that the `<content />` elements are invalid and the parser adds them as a child node of the previous one. Which results in a document which is multiple thousands of elements deep.

The `QuerySelectorAll` implementation uses recursion which then results in a very deep stack trace.

I have submitted #524 which does not use recursion and fixes this bug.

**Comment by FlorianRappl** [comment] 2017-01-28 19:25
I think its a valid test and the recursion here should be improved. But keep two things in mind

1. No existing test should fail
2. The performance should be at least as it is now (actually I think this one should be a performance boost for queries if done right)

Thanks for reporting the issue and working on a fix 👍 !

**Closed as completed** 2017-02-08 22:20 UTC
Labels: bug, performance, dom
