### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by YakupIpek** [AngleSharp/AngleSharp#556] opened 2017-05-02 22:43 UTC
I know that it is hard to fix issue when it is not reproducible but this is one of that case where i can not reproduce this error. Our crawler works 2-3 days and stop permanently and gives below exception. I have to restart application when this is happened.

AngleSharp version is 9.9.
.Net version is 4.6.1

Let me know if is there anything you need to know more.

```
System.InvalidOperationException: Exception of type 'System.InvalidOperationException' was thrown.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.VerifyIntegrity()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   at AngleSharp.Dom.Node..ctor(Document owner, String name, NodeType type, NodeFlags flags)
   at AngleSharp.Dom.Document..ctor(IBrowsingContext context, TextSource source)
   at AngleSharp.Dom.Html.HtmlDocument.<LoadAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.BrowsingContextExtensions.<OpenAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NinjaSpider.Engine.WebsiteCrawler.<GetHtmlDocumentAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NinjaSpider.Engine.WebsiteCrawler.<GetPageInfoAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NinjaSpider.Engine.SpiderQueue.<CrawlPageAsync>d__19.MoveNext() 
```

**Comment by FlorianRappl** [comment] 2017-05-03 05:51
Sounds like a duplicate of #505 - maybe it is possible to get more info this time.

Are you using multiple threads?

**Comment by YakupIpek** [comment] 2017-05-03 11:29
Yes it is multi-threaded application but returned instance from`BrowsingContext.New()` is not referenced on a property or field so returned object from `BrowsingContext.New()` is not shared between threads. Is it clear what i am trying to explain for you ?

I wanted to reproduce this issue but i couldn't. Let me know if you have any other question.

**Comment by FlorianRappl** [comment] 2017-05-03 11:48
Since it is an issue in the `ConditionalWeakTable` it will be quite hard to reproduce. Apparently, the integrity check has failed. That could either be a memory corruption or a hiccup in the CLR (essentially switching the `_invalid` flag).

**Comment by YakupIpek** [comment] 2017-05-03 19:53
I don't think that is related to memory corruption or CLR. Older versions of AngleSharp hadn't such a issue probably. This issue happens in every 1-2 days so i don't think that memory corruption can be happen such frequently.

**Comment by FlorianRappl** [comment] 2017-05-03 21:22
"Older versions": Some potentially yes (the more recent ones that used the `ConditionalWeakTable `).

Well, again the issue is in the CLR (see stacktrace). If you look at the code of the `ConditionalWeakTable` you will see that there should (under normal operation) actually never be a failed integrity check.

I'm a little bit lost here without further context. Even though I believe that you use one context per thread (or something around that) I doubt its one document per thread. The description seems to indicate some kind of race condition.

**Comment by YakupIpek** [comment] 2017-05-04 12:48
There can not be race conditions because BrowsingContext.New() returned instance is never shared between threads. 

Are you doing write operation on static field in somewhere ?

**Comment by FlorianRappl** [comment] 2017-05-04 13:04
It is not about the context, but rather about the documents. The `ConditionalWeakTable` is the type of a static field in the document. It is used to attach further properties to document instances.

**Comment by YakupIpek** [comment] 2017-05-04 13:40
How can you modify static field in your own library without having issues on multi-threaded application ? I definitely believe that those fields should not be static.

**Comment by YakupIpek** [comment] 2017-05-04 20:55
Here is another exception from our logs which is OutOfMemoryException

```
Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Resize()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.CreateEntry(TKey key, TValue value)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   at AngleSharp.Dom.Node.AppendText(String s)
   at AngleSharp.Parser.Html.HtmlDomBuilder.AddCharacters(String text)
   at AngleSharp.Parser.Html.HtmlDomBuilder.InBody(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Home(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.Consume(HtmlToken token)
   at AngleSharp.Parser.Html.HtmlDomBuilder.<ParseAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Parser.Html.HtmlParser.<ParseAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by FlorianRappl** [comment] 2017-05-04 21:00
I suppose you don't dispose the documents properly. Thus the document as well as its children stay in memory.

**Comment by YakupIpek** [comment] 2017-05-04 21:13
I haven't seen that anything disposed in the examples. Can you point me an example which i can follow ?

**Comment by YakupIpek** [comment] 2017-05-04 21:20
Here is how i am obtaining document and Content method parameter is string so i don't pass stream parameter there. Is there anything to be disposed in this case ? 

`await BrowsingContext.New().OpenAsync(r => r.Address(uri).Content(content))`

**Comment by ushenkodmitry** [comment] 2017-05-05 08:10
Nothing special. Just use "using":
```
using(IDocument document = await BrowsingContext.New().OpenAsync(r => r.Address(uri).Content(content)))
{
}
```

**Comment by YakupIpek** [comment] 2017-05-08 16:47
Is there anything to be disposed when content parameter is string ? I want to know that am i missed something critical on this.

**Comment by FlorianRappl** [comment] 2017-05-08 20:50
All the content needs to be disposed. .NET GC does not like cyclic dependencies which are given in this case (a node has children, each child has a parent).

The dispose is more or less just disconnecting the children from the document. There are some actions - all of which just to ensure the GC can work most efficiently.

**Comment by YakupIpek** [comment] 2017-05-23 16:02
@FlorianRappl  I wanted to give an update. System stability seems improved and it looks we haven't yet hit that exception again. Probably system were hitting out of memory exception and constantly getting that error. I think this was happening when there is workload on system. 

I am still observing and i will keep you updated.

**Comment by georgiosd** [comment] 2017-05-23 17:38
@YakupIpek maybe try the modification from my PR in the cache class that uses the table - I think the previous version was prone to race conditions.

**Comment by FlorianRappl** [comment] 2017-05-23 21:56
Thanks for the info!

**Closed as completed** 2017-07-19 01:34 UTC
Labels: bug, dom
