### ISSUE TITLE
Comments missing in Css output generated using .ToCss method and a formatter

### ISSUE THREAD

**Issue by rsuk** [AngleSharp/AngleSharp#230] opened 2016-01-03 19:41 UTC
When generating output from a modified Stylesheet document, the comments appear to be lost. My code looks something like this:

```
CssParserOptions options = new CssParserOptions();
options.IsStoringTrivia = true;
CssParser parser = new CssParser(options);
string CssSource = null
// Read from file code here
AngleSharp.Dom.Css.ICssStyleSheet document = parser.ParseStylesheet(CssSource);
AngleSharp.Css.PrettyStyleFormatter formatter = new AngleSharp.Css.PrettyStyleFormatter();
string newCssSource = document.ToCss(formatter);
```

I have also tried the CssStyleFormatter but that also seems to discard the comments. From a quick look at the code it looks as though the formatter only outputs Rules and not the comment nodes that I can see as Children under the document in debug. 

I did fudge the code to write out comments, and noticed that the comments are output incorrectly (as "comment text /\* */") - looks like this code in CssStyleFormatter.Comment is the culprit:

```
return String.Join("/* ", data, " */");
```

.. this will join the second 2 arguments with a separator of the first argument, which I'm pretty sure wasn't the intention. For my fudge, I changed it to this:

```
return String.Format("/* {0} */", data);
```

**Comment by FlorianRappl** [comment] 2016-01-03 20:27
Yes of course, this should have been `String.Concat`. Right now the `ToCss` is still the same as the `CssText` for most CSS nodes. Therefore, it mirrors the behavior of browsers, which discard the CSS comments. In the future they will diverge, i.e., while `CssText` produces the browser's output, `ToCss` will be a serialization of the contained OM. However, in general both won't reproduce the original source text. The original source text can only be reproduced by printing the relation to the original source.

**Comment by rsuk** [comment] 2016-01-03 20:42
I recognize that reproducing the original source text isn't always going to be possible, but not being able to retain comments would make any kind of use for roundtrip css manipulation impractical in real world scenarios (where the css may contain invaluable comments) - a task for which AngleSharp is otherwise ideal. The nodes for document level comments are certainly there in the OM (Children collection) at present; the fudge I'm working works fine for document level comments.

Is there a logical workaround I can implement for comments within the rule body as well as those at the document level, given what is available in the OM right now do you think?

**Comment by FlorianRappl** [comment] 2016-01-03 21:45
The workaround I see is to generate the string representation and insert the comments afterwards at their proposed locations.

Generally, CSS comments may appear at any position (basically almost everywhere, where a whitespace could be placed), which does not map nicely to a concept of child nodes, i.e., just because a comment is a child node of, e.g., a rule, does not mean that it is in fact contained within that rule. It could be overlapping, e.g., being placed inside a prelude of that rule.

**Comment by rsuk** [comment] 2016-01-03 22:14
Thanks for the insight. It would be a real shame to lose all source comments because of some edge case scenarios - in the example you describe outputting the comment inside the rule would be significantly better than dropping it completely and crucially wouldn't lose any information.

**Comment by FlorianRappl** [comment] 2016-01-03 22:28
Well, as I wrote in my initial answer, ultimately, nothing is lost. Also `ToCss` will be different to `CssText`. And finally, I will try to master these edge cases. For now, just placing the comments at their original positions should be sufficient.

The bug will be fixed with this issue, the other enhancements will be related to this issue, but I can't promise that they (all) make it into the next release (v0.9.5).

**Closed as completed** 2016-03-16 22:21 UTC
Labels: bug, enhancement
