### ISSUE TITLE
Use AngleSharp For Strip Html - Performance

### ISSUE THREAD

**Issue by vinh84** [AngleSharp/AngleSharp#366] opened 2016-07-11 08:34 UTC
Hi AngleSharp ,

I love your lib very much, thank you.

I want to switch from HtmlAgilityPack to AngleSharp for strip html to text.
But i have some performance issue. It's slower HtmlAgilityPack  
10x

Test Code Attached
[test.zip](https://github.com/AngleSharp/AngleSharp/files/356717/test.zip)

**Comment by FlorianRappl** [comment] 2016-07-11 09:18
Thanks for your interest. However, this is not a real benchmark. You are basically ignoring most things that are important when trying to conclude on performance. Mostly, Jit warmup times are significant in managed applications. Also Garbage Collection may interfere with out measurement and mostly the amount of work you are doing is quite small. Therefore, for anything that has to look serious I would recommend you to either invest more in such a benchmark, or just use [BenchmarkDotNet](https://github.com/PerfDotNet/BenchmarkDotNet).

Also even though you tried to make the code look similar, they are not. AngleSharp is actually doing more work (e.g., the `All` property returns the result of a selector - therefore all the nodes have already been iterated and included in a list).

AngleSharp as a library is more heavy-weight than the agility pack (there are multiple reasons for this, but that's just the way it is). Hence jitting it takes more time.

I am closing this as a duplicate of #97, even though I am convinced that the absolute (!) difference is marginal and negligible in this scenario.

**Closed as completed by FlorianRappl** 2016-07-11 09:18 UTC
Labels: duplicate, invalid

**Comment by matthewDDennis** [comment] 2019-06-04 22:48
I changed the test to run 1 pass on each version to warm up, and the time 10 runs on each.
```
Warming up ...
Running tests ...
For 10 runs each: AngleSharp 00:00:00.0518069 vs HtmlAgilityPack 00:00:00.0346357
```
Pretty close
