### ISSUE TITLE
Custom property names in Var declarations should preserve case

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#82] opened 2015-04-30 07:44 UTC
I think there may be an incorrect case conversion in AngleSharp. Parsing this css input:
`p { border-color:var(Body) }`

Results in a `CssUnknownProperty` where `Value.CssText` is `var(body)`, with the property value changed to lower case, from `Body` to `body`.

The css-variables [specification](http://www.w3.org/TR/css-variables/#funcdef-var) states this:
"Unlike other CSS properties, custom property names are case-sensitive."

Edit: There seems to be another case: Parsing this:
`:root { font-family: Tahoma; }`
Results in a property of type `CssFontFamilyProperty`. Its `Value` is of type `CssIdentifier`.
The `Value` of this `CssIdentifier` is `tahoma` so once again the value has been changed to lower case.

**Comment by FlorianRappl** [comment] 2015-04-30 14:14
I guess you mean the value - the property name is `border-color` (or `font-family` in the second case). Nevertheless, yes, at the moment every identifier is stored as lowercase, which simplifies comparisons, but may have some impact in special scenarios. Since the CSS value model is about to be finalized for v0.9, I will most probably preserve the case for unknown / invalid values.

**Comment by corliss** [comment] 2015-04-30 14:42
Thanks. Just to make sure I'm communicating this correctly, There are two separate issues reported here:

1) The first is related to the css-variables specification. This is a very particular case, and can be fixed by fixing `CssUnknownProperty` as you suggest. 
2) The second has to do with `CssIdentifier` in the specific situation I've described. (There may be others as well, I don't know.)

Both these issues violate the css specifications. Do you agree that these are bugs? I am a little confused by the "enhancement" label you added.

**Comment by FlorianRappl** [comment] 2015-04-30 14:57
Yes, both issues noted. Regarding "enhancement": AngleSharp tries to be as close as possible to the behavior of real browsers, which (should) follow the specification. Any action to achieve this goal is an enhancement. The current CSS model is not perfect, but the behavior you described was intended at some point and therefore is no bug.

**Comment by corliss** [comment] 2015-04-30 15:42
Sorry, still confused. Is there a way to get the text with the actual case, similar to what you suggested in the previous issue I opened?

If there isn't then it seems like major functionality - font family names and css variables - will not work. Am I missing something?

**Comment by FlorianRappl** [comment] 2015-04-30 17:05
I am missing the point: Why are you interested in the case? What is the case telling you? CSS identifiers are case-insensitive.

**Comment by corliss** [comment] 2015-04-30 17:44
I'll answer separately for each of the cases:

1) From your answer it appears you may be unaware of Css Custom Properties. The Css Custom Properties specification http://www.w3.org/TR/css-variables/#funcdef-var defines a new type of css declaration, using variables. You can declare a variable (also called a custom property) like this:
`:root { var-Body: Tahoma; }`

The name of the variable is `Body`. The `var-` prefix tells css that this is a custom property. Placing this within `:root` makes the variable available to all elements.
You can then use the variable in another part of the css like this:
`p {font-family: var(Body);}`

In this case the same variable name, case-sensitive, must be specified inside the `var()`.
According to the specification, the css engine should compute this as
`p {font-family: Tahoma;}`

Because AngleSharp strips the case from the identifier this gets turned into
`p {font-family: var(body);}`
and so lookup fails, because this css specification http://www.w3.org/TR/css3-syntax/#style-rule _specifically_ mentions that
"The names of Custom Properties [CSS-VARIABLES] are case-sensitive."

Note: AngleSharp obviously does not yet have any code that implements this css-variables specification. That's ok, my code takes care of that. However my code uses AngleSharp to parse css. Because the css parser strips the case, I don't have any way to work around this bug. So the right thing is for AngleSharp to preserve case for custom properties, _or_ provide an alternate way to get the exact text.

[At some point if AngleSharp intends to be a full css3 implementation it will also need to fully implement the Css Custom Property specification. But as I mentioned in the previous paragraph, I don't need that, but I do need the exact text.]

2) The name of a font is something that can be displayed to the user, e.g. when the user clicks on some text in a word processor that uses CSS under the covers. If the parser converts the name to lower case, this creates ugly text. Therefore the original text should be preserved in some way.

See this stackoverflow thread for more information: http://stackoverflow.com/questions/1602586.

**Comment by FlorianRappl** [comment] 2015-04-30 18:07
1) Yes, I am aware of that, but a) this module is not implemented in AngleSharp at all and b) it does not matter since (as mentioned above) all identifiers are treated as CSS identifiers [and not variables, which preserve case]. To support this a CSS unknown value has to be produced. See the next point.
2) Since `font-family` treats identifiers like strings, this won't be a problem in the future, where values are created by the declaration (property) and not the value factory. Therefore a special case such as `font-family` will preserve case, whereas other identifiers will be converted to their corresponding enumeration value (which is lowercase).

Right now every value gets created by the parser. This has some limitations, which is why parts of AngleSharp's CSS already changed. In the future the values will be created by their declarations. Also one will be able to access computed properties. However, unlike a former approach, the approach will require providing device information.

**Comment by corliss** [comment] 2015-04-30 18:12
OK. In the meantime, do you have any workarounds or suggestions? These are blocking issues for me. I am in the process of trying to use AngleSharp as a css parser (instead of my existing parser) and these are the two remaining issues as far as I can tell.

Any suggestions/workarounds/fixes will be very helpful.

**Comment by FlorianRappl** [comment] 2015-05-04 08:49
I am currently working on that -- right now there is no workaround, but I plan on releasing AngleSharp v0.8.4 soon; which will include a solution to this problem (and maybe also some other problems / enhancements).

The new value model won't be fully implemented yet, however, it will be one step closer and it will certainly contain preservation of case for unknown properties and unknown values (every value used in an unknown property is also an unknown value according to the new model).

AngleSharp v0.8.4 will be released within this or next week.

**Comment by corliss** [comment] 2015-05-04 10:00
Thanks, that's very good to hear.

**Comment by corliss** [comment] 2015-05-27 16:29
Hi, not sure if the current code is supposed to fix this, but I tried it anyway, using
`p { border-color:var(Body); }`

Unfortunately, parsing does not produce any declarations for this.

As an experiment, if the property name `border-color` is changed to an unknown property, e.g. 
`foo:var(Body);` 
then parsing does produce a `CssUnknownProperty`, and the case of `Body` is indeed preserved (which did not happen in earlier builds of AngleSharp.) 

Alternately, changing the _value_ to a known color, e.g.
`border-color:red;`
also parses correctly.

Just FYI, in my use of AngleSharp as a CSS parser, I'm not using the strongly typed values such as BorderLeftColor etc. I just uniformly need the text property name and text property value in all cases, known or unknown.

**Comment by corliss** [comment] 2015-05-27 16:35
Just a comment - if AngleSharp could avoid throwing away legal CSS properties it does not understand, that would be great. There are all kinds of new CSS properties being created, as well as new syntax for existing properties. These are all legal CSS, and having them be thrown away is imho a quite serious bug that is hard to track down.

**Comment by FlorianRappl** [comment] 2015-05-27 16:53
This is already integrated in the new version (which will be released as v0.8.4). Unknown properties are not thrown away, however, I don't know if they will be serialized in the CSSOM way. But in C# / non-W3C API you will be able to access them. Please note that such unknown properties will also have unknown values, which are neither validated, nor sanitized. Hence identifiers won't be lower-cased, colors won't be normalized, ...

**Comment by corliss** [comment] 2015-05-27 16:57
Thanks. 

By "new version" do you mean the current code checked in to github, or some private code that isn't in github yet? I ask because the error above was reproduced on the latest github code.

**Comment by corliss** [comment] 2015-05-27 18:44
FYI - I was able to work around this bug by modifying `CssProperty.TrySetValue()` to set `_value = value` and return `true` if the `if` and `else` clauses do not execute. I have made several local changes for my own needs and will gather these into a pull request at some point.

At this point I've decided to switch from my previous ANTLR based parser to AngleSharp - so that's a vote of validation for your efforts. Great work :)

**Comment by FlorianRappl** [comment] 2015-06-04 07:41
So in v0.8.4 there is no serialization rule for identifiers. There are other serialization rules for values, which may affect you; such as automatic hex-color to rgb-function serialization, but they will probably also change / improve in v0.9.

Currently the problem is to distinguish between an accepted normalized form and a "wild" form. Only a valid declaration could change the mode, but this is very annoying for me - since there are a lot of declarations. The real deal is to find a unified model, which covers most cases and is easy to manipulate for the edge cases (such as unknown declarations or declarations with special rules such as `font-family`).

**Closed as completed by FlorianRappl** 2015-06-04 07:41 UTC
Labels: bug, enhancement

**Comment by corliss** [comment] 2015-06-04 12:49
Is the present bug fixed, though? I can't tell from your comment.

When you earlier stated that this issue was fixed, the code at the time did not reflect this - please see my earlier edit regarding `p { border-color:var(Body); }` - no declarations _at all_ were being produced for this.

You may be thinking of something else, so please read my earlier edit carefully...

**Comment by FlorianRappl** [comment] 2015-06-04 14:35
In the case you specify the value is invalid and therefore not considered. This is by definition. This is no bug and intended. If you specify `my-color` instead of `border-color`, then the declaration is of unknown type and therefore the value validation is turned off, which gives you what you want. This was all discussed earlier.

Maybe in AngleSharp v0.9 the underlying CSSOM changes more, but in v0.8.4 this is as far as I could go. Other changes may take longer and changing the whole underlying model is a huge effort.

**Comment by corliss** [comment] 2015-06-09 08:13
I don't understand - this is not invalid css, see above. Firefox supports this already.

If you can't fix the bug yet, I can understand, but why close the issue?

Isn't it better to keep the issue open until a fix is available?

**Comment by FlorianRappl** [comment] 2015-06-09 15:14
Everything is invalid CSS unless supported. Declarations need to know which values to consider valid and invalid.

For your specific request (which would be "allow arbitrary values") there is currently no "fix" or "solution" available; but I am working on something for version v0.9. So it will come. But you will have to call the `CssParser` directly. In the end you will need to turn off declaration validation - which is not possible yet (and not desired; unless if you want to use AngleSharp for e.g., an authoring tool - which is I guess exactly your scenario).

AngleSharp v0.9 will provide such modes. But it will take me a few more weeks to finish this (work on that has already started).

BTW: I closed the issue since I considered the state of the issue a "won't fix" / "is implemented" (first one related to known declarations, second one to unknown declarations / known ones with exceptions, e.g., `font-family`). However, the changes I am talking above (in v0.9) will also enable the document round-tripping, which is discussed in an issue that is still open. So don't worry; these things are definitely still on the radar.
