### ISSUE TITLE
Consider adding attribute text position info to HtmlTagToken

### ISSUE THREAD

**Issue by yufeih** [AngleSharp/AngleSharp#766] opened 2019-03-11 06:43 UTC
We are using AngleSharp to manipulate HTML in an authoring workflow, so we want to preserve the original HTML content as much as possible, including all the spaces and bad syntax, etc.

With #636 , I am able to retrieve source text position information for tags, but `Attributes` does not currently have position info, this prevents us from doing stuff like changing all the link urls without touching other parts of HTML.

`HtmlAgilityPack` has a `ValueStartIndex` and `ValueStartLength` property for each attribute.

The proposal is to provide the same text position information to HTML attributes in the tokenization layer.

**Comment by FlorianRappl** [comment] 2019-03-11 09:32
Is this a duplicate of #754?

(Note: Having an index on one node (e.g., element) is for me the same as having the index on other nodes (e.g., attribute); hence my question)

**Comment by FlorianRappl** [comment] 2019-03-23 18:00
I think this should be doable. Thanks for the suggestion!

**Comment by FlorianRappl** [comment] 2019-04-28 08:28
Landed in `devel`.

**Closed as completed by FlorianRappl** 2019-04-28 08:28 UTC
Labels: enhancement, parser, up-for-grabs, html

**Comment by yufeih** [comment] 2019-07-01 06:14
@FlorianRappl , `HtmlAttributeToken.Position` currently points to attribute name start index, can there be an `HtmlAttributeToken.ValuePosition` that points to attribute value start index?

**Comment by FlorianRappl** [comment] 2019-07-01 06:57
@yufeih good suggestion; I think this should be doable.
