### ISSUE TITLE
Two ContextLoadingTests fail with DirectoryNotFoundException when running tests by dotCover

### ISSUE THREAD

**Issue by HellBrick** [AngleSharp/AngleSharp#483] opened 2016-12-04 14:50 UTC
The tests are `LoadContextFromStreamLoadedShouldNotBeStuckForever` and `    LoadContextFromStreamLoadedShouldNotFaceBufferTooSmall` and they both fall with the similar exception, only the file name differs:
```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\HellBrick\AppData\Local\Temp\alby2xhq.a1k\aqkizyvj.bqc\AngleSharp.Core.Tests\assembly\dl3\Resources\kommersant.ru-1.res'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at AngleSharp.Core.Tests.External.PageRequester.<AddResourceAsync>d__6.MoveNext() in F:\Software\AngleSharp\src\AngleSharp.Core.Tests\External\PageRequester.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Core.Tests.External.PageRequester.<PerformRequestAsync>d__4.MoveNext() in F:\Software\AngleSharp\src\AngleSharp.Core.Tests\External\PageRequester.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Io.BaseRequester.<RequestAsync>d__6.MoveNext() in F:\Software\AngleSharp\src\AngleSharp\Io\BaseRequester.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Io.BaseLoader.<LoadAsync>d__14.MoveNext() in F:\Software\AngleSharp\src\AngleSharp\Io\BaseLoader.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.BrowsingContextExtensions.<OpenAsync>d__2.MoveNext() in F:\Software\AngleSharp\src\AngleSharp\BrowsingContextExtensions.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AngleSharp.Core.Tests.Library.ContextLoadingTests.<LoadContextFromStreamLoadedShouldNotFaceBufferTooSmall>d__9.MoveNext() in F:\Software\AngleSharp\src\AngleSharp.Core.Tests\Library\ContextLoading.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```

If I understand correctly, the tests assume that `AngleSharp.Core.Tests.dll` is located in a very specific path related to the repository's `\src\AngleSharp.Core.Tests\Resources` folder, and things break if the project is build to a different folder or the test runner does some trickery. Not sure what would be the best way to make these tests more robust, maybe adding the files to the dll resources and then using them directly from there (or writing them to the temp folder inside the tests if they must be located on disk)?

**Comment by FlorianRappl** [comment] 2016-12-04 14:54
Well, these tests are designed such that they *are* robust. The problem with tests from webpages we don't control is that they may change and thus the test may fail even though everything's perfect fine.

The solution is a lightweight *local* wrapper that assumes a certain convention to be followed. Another solution may have been to actually use the test website for caching other websites. I decided to go for the former to have running tests even without Internet connection (there are enough integration tests already that require Internet connection). So I close this for now as the problem is in breaking the convention, not the code itself. It was not written to be used in other cases.

I would consider it an enhancement to change the tooling here, but frankly I don't like having a configuration just to make the tests working - if they are used as they should be then they are working.

**Closed as completed by FlorianRappl** 2016-12-04 14:54 UTC
