### ISSUE TITLE
Encoding detection broken

### ISSUE THREAD

**Issue by GieltjE** [AngleSharp/AngleSharp#447] opened 2016-10-26 08:30 UTC
For some reason the parser will fallback to the last encoding inserted into the list (https://gitlab.com/Shushpanov/AngleSharp/blob/c1912dc8ad546204b3dae1fc4a278018509c3d38/AngleSharp/Foundation/DocumentEncoding.cs).

Proof (C# uses UTF-16 for strings, so it should fallback to UTF-8 in a worst case scenario): 
`HtmlParser parser = new HtmlParser();
parser.Parse("<HTML></HTL>");`
And (appears to be proper UTF-8):
`HtmlParser parser = new HtmlParser();
parser.Parse(webClient.OpenRead("http://slashdot.org");`

Both result in: System.ArgumentException: ''iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'

When overriding the DownloadString of the WebClient the HttpWebResponse characterset also reports UTF-8.

Also IMO we should be able to force a certain encoding, that would solve most of the problems (I am fully aware that this is sketchy at best, but the default WebClient is also wrong (it defaults back to your current non-utf windows setting). But at least that can be fixed by extending it and overriding the functions with a custom characterset parser).

**Comment by ushenkodmitry** [comment] 2016-10-26 09:25
Possible duplicate of #326

**Comment by GieltjE** [comment] 2016-10-26 09:25
Correct, but #326 is closed but stil obviously broken.

**Comment by ushenkodmitry** [comment] 2016-10-26 09:42
Look @FlorianRappl 's answer

> Unfortunately, I can't fix the .NET framework. Depending on the platform one or the other encoding may not be available.

This exceptions originates from the .Net framework. Hitting F5 will continue your program.

**Comment by GieltjE** [comment] 2016-10-26 09:43
I know that, I have read the old reports.

What I do not understand is why we should not be able to pass an extra variable with a forced encoding.

**Comment by FlorianRappl** [comment] 2016-10-26 10:42
You can always insert your own middleware to download a document and convert to another encoding. However, if you don't do anything AngleSharp will pick the right encoding for you. On some platforms (as noted) not all encodings will be available. As a fallback UTF-8 will be used.

Additionally, sometimes it is not possible to determine the encoding of a document (no BOM, no encoding header, no meta tag). In such cases the encoding service is used - which you can provide. The default service follows the W3C specification and uses a locale-based mapping to return the encoding to use.

**Closed as completed by FlorianRappl** 2016-10-26 10:42 UTC
Labels: invalid

**Comment by GieltjE** [comment] 2016-10-26 10:47
How do I pass it to the parser with proper encoding? If it is in a string with UTF-8 encoding it still fails......

**Comment by FlorianRappl** [comment] 2016-10-26 10:51
A string is UTF-16 (this is the .NET Framework). So your "string" is either a series of bytes, or you already made a mistake in the first place.

Why don't you use the browsing context? Why don't you just create a virtual response from a stream accessing the UTF-8 content bytes? That would instantly help you.

Hope this helps!

**Comment by GieltjE** [comment] 2016-10-26 11:04
Because it has the same problems and doesn't accept a encoding override.

**Comment by ushenkodmitry** [comment] 2016-10-26 12:47
This may help #324 :-)

**Comment by FlorianRappl** [comment] 2016-10-26 12:57
> Because it has the same problems and doesn't accept a encoding override.

In a response you can set the encoding via the HTTP response header. So much for your encoding override. Also read carefully the issue @ushenkodmitry mentioned.
